remote_theme: pmarsceill/just-the-docs

title: JavalinVC
description: A View COntroller system for Javalin
baseurl: "/JavalinVC"
url: "https://kingtux.dev"
color_scheme: "dark"
aux_links:
  "Javalin on GitHub":
    - "//github.com/wherkamp/javalinvc"
  "SimpleSite":
    - "https://kingtux.dev/simpleSite"