remote_theme: pmarsceill/just-the-docs

title: JavalinVC
description: A View Controller system for Javalin
baseurl: "/javalinvc"
url: "https://kingtux.dev"
color_scheme: "dark"
aux_links:
  "JavalinVC on GitHub":
    - "//github.com/wherkamp/javalinvc"
  "Javalin":
    - "https://javalin.io/"
  "SimpleSite":
    - "https://kingtux.dev/simplesite/"
